name: CI/CD - Build & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:version1
             
             

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push   # Wait for the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH keydeploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 777 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy container on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Logging into DockerHub..."
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"

            echo "Pulling latest image..."
            docker pull dhankhar9918/flip-kart-app:mariov1

            echo "Stopping and removing old container (if exists)..."
            docker stop flipkart-container || true
            docker rm flipkart-container || true

            echo "Running NEW container..."
            docker run -d --name flipkart-container -p 80:80 dhankhar9918/docker_image:version1
          EOF
